version: '3'
services:
  db:
    image: 'postgres'
    container_name: 'my_postgres'
    environment:
      - POSTGRES_DB=db_corion
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
